name: Update Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *'  # runs daily at 12 AM IST

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --remote --merge

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "🔄 Automated update of submodules" || echo "No changes to commit"
          git push origin main
