name: Update Submodules

on:
  schedule:
    - cron: '0 18 * * *'  # Runs daily at 12 AM IST (18:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Update submodules
      run: |
        git submodule update --remote --merge

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "🔄 Automated submodule update" || echo "No changes to commit"
        git push origin main
